// we didnt have time to implement the vector data base so heres a fast implemention instead LOL
// each cell will contain a key word that will be used to match the user input and a propmt that will be sent to the model

const prompts = [
  {
    title:
      "Shuttle External Tank Engine Cut Off Feed Through Connector Failure",
    prompt:
      "Lesson(s) Learned Electrical connector integrity can be significantly impacted at cryogenic temperatures. The mechanical design of electrical connectors can be affected by environmental conditions at cryogenic operating temperatures that may not be obvious to electrical or electronic design disciplines. \nRecommendation(s) Changes to electrical systems should be reviewed for failure modes other than strictly “electrical” causes; mechanical response of sensors to extreme environments is a broadly applicable area of concern in system design at NASA. Operating environments and their potential effects on materials and mechanisms should be identified and mitigated as early in the design process or the design change process so that the problem is not first detected when the vehicle is sitting on the launch pad. Operational check-out procedures could be reviewed to determine if changes to check-out sequences could identify potential problems prior to a launch attempt. The information learned from the Centaur Program should have been communicated to the vendor or to some industry wide bulletin board. The vendor then should have taken responsibility to notify other users of the product of the potential problem that may exist in their application if used in similar conditions, and of any corrections or fixes to the problem. The process could be similar to a Government-Industry Data Exchange Program (GIDEP) alert or an information bulletin from an automobile manufacturer about a potential defect. Keep the vendors involved.",
  },
  {
    title: "Latching Safety Critical Signals in Pyrotechnic Circuits",
    prompt:
      "A number of simple enhancements can be made to improve this design. The preferred method would be to qualify the data signal. This is possible if the source of the signal is coming from a circuit that can also produce a qualifying data strobe indicating that the data is valid. For example, if the signals come from a microcontroller (as was the case with the system that misfired) two  output ports could be  used in the configuration as shown in Fig. 2.  This circuit has the advantage that the F/F will only be set  when DATA is coincident with the positive edge of the STROBE; at other times the F/F will be immune to noise. In pyro control  systems that use a 2-phase ARM and FIRE control approach, the ARM control can potentially be used on the DATA input and the FIRE control can be used to latch the DATA on the STROBE input. When a DATA/STROBE configuration is not possible other techniques can be used to improve noise immunity. A simple RC low pass filter shown in Fig. 3 can be added to the clock line in Fig. 1. This will attenuate noise above the cutoff  frequency (fc) where fc=1/ (2 π RC). A word of caution with this approach, some F/Fs will not operate properly if the clock edge transitions too slowly. One should use a F/F (i.e. 74LVC1G74) with a Schmitt trigger on the clock input that can tolerate a slow clock rise time, or the design should include an  external Schmitt trigger. Alternately a debouncer (i.e. LCT6994) shown in Fig. 4 can used as a low-pass filter. A delay value can be set with an external  resistor network as shown. In this configuration, the input signal must be stable for 100ms before the output changes; short pulses are ignored (filtered). For this to be effective, the debouncer and F/F of Fig.1 should  be located near each other to minimize the signal path. It is also possible to apply a combination of techniques to ensure correct data latching. Lastly, confirming the design noise margin, either by test or via analysis when test is impractical, to inadvertent firing is important in a system where an inadvertent fire is catastrophic. This margin should be on critical control inputs in thresholding logic ahead of the fire control inhibit semiconductor switches. Per specifications that date back to MIL-STD-1576, the  noise floor during tests does should not reach ½ the threshold voltage (6 dB) to activate the devices. ",
  },
];

export default prompts;
